# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Sets current start folder, and loads parent Vagrantfile
UMBOX_FOLDER = File.dirname(__FILE__)
VM_NAME = File.basename(UMBOX_FOLDER)
load File.expand_path(UMBOX_FOLDER + '/../common/Vagrantfile', __FILE__)

# All Vagrant configuration is done below.
Vagrant.configure(2) do |config|
  # Copy all files to the VM, and set up depdencies and service.
  config.vm.provision "file", source: UMBOX_FOLDER + "/setup_squid.sh", destination: "$HOME/squid/setup_squid.sh"
  config.vm.provision "file", source: UMBOX_FOLDER + "/squid.service", destination: "$HOME/squid/squid.service"
  config.vm.provision "file", source: UMBOX_FOLDER + "/squid.conf", destination: "$HOME/squid/squid.conf"  
  config.vm.provision "shell" do |s|
    s.path = UMBOX_FOLDER + "/umbox_setup.sh"
  end

end
