# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Sets current start folder, and loads parent Vagrantfile
UMBOX_FOLDER = File.dirname(__FILE__)
load File.expand_path(UMBOX_FOLDER + '/../snort-base/Vagrantfile', __FILE__)

# All Vagrant configuration is done below.
Vagrant.configure(2) do |config|
  # Copy all files to the VM, and set up dependencies and service.
  config.vm.provision "file", source: UMBOX_FOLDER + "/snort.conf", destination: "$HOME/snort/snort.conf"
  config.vm.provision "file", source: UMBOX_FOLDER + "/local.rules", destination: "$HOME/snort/local.rules"
  config.vm.provision "shell" do |s|
    s.path = UMBOX_FOLDER + "/umbox_setup.sh"
  end
end
