# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Sets the VM name to the same name as the folder we started from.
VM_NAME = File.basename(UMBOX_FOLDER)

# Loads common_Vagrantfile
load File.expand_path(UMBOX_FOLDER + '/../common/Vagrantfile', __FILE__)

# All Vagrant configuration is done below.
Vagrant.configure(2) do |config|

  # Copy all sniffer files to the VM, and set up depdencies and service.
  config.vm.provision "file", source: "../../sniffer", destination: "$HOME/"
  config.vm.provision "file", source: "../sniffer_vm_base/sniffer.service", destination: "$HOME/sniffer/sniffer.service"
  config.vm.provision "shell" do |s|
    s.path = "../sniffer_vm_base/sniffer_setup.sh"
    s.args = ["/home/" + VM_USER + "/sniffer"]
  end

  # Copy a properly configured alerter config file for this software to the VM, and restart alerter.
  config.vm.provision "file", source: "../sniffer_vm_base/config_alerter.json", destination: "$HOME/alerter/config.json"
  config.vm.provision "shell", inline: "systemctl restart alerter"

  # Copy specific config file, and restart sniffer to use it.
  config.vm.provision "file", source: UMBOX_FOLDER + "/config.json", destination: "$HOME/sniffer/config.json"
  config.vm.provision "shell", inline: "systemctl restart sniffer"

end

