# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Sets current start folder, and loads parent Vagrantfile
load File.expand_path(UMBOX_FOLDER + '/../sniffer_base/Vagrantfile', __FILE__)

# All Vagrant configuration is done below.
Vagrant.configure(2) do |config|

  # Copy all httpserver files to the VM, and set up depdencies and service.
  config.vm.provision "file", source: "../proxy_base/httpserver.service", destination: "$HOME/sniffer/httpserver.service"
  config.vm.provision "file", source: "../proxy_base/httpserver.sh", destination: "$HOME/sniffer/httpserver.sh"
  config.vm.provision "shell" do |s|
    s.path = "../proxy_base/httpserver_setup.sh"
    s.args = ["/home/" + VM_USER + "/sniffer"]
  end

end

