# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

BASELINE_BOX = 'generic/ubuntu1604'
VM_USER = 'vagrant'

Vagrant.configure(2) do |config|

  # Base and name setup.
  config.vm.box = BASELINE_BOX
  config.vm.hostname = 'umbox-baseline'

  # Keep default keys to simplify repackaging.
  config.ssh.insert_key = false

  # Add additional NICs for performing middlebox operations.
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "private_network", ip: "10.1.1.10"
  config.vm.network "private_network", ip: "10.1.2.10"

  # NOTE: this is only needed if behind a proxy.
  #config.vm.provision "shell", path: "../baseline/proxy_setup.sh"

  # Setup general baseline things.
  config.vm.provision "file", source: "./setup_iptables.sh", destination: "$HOME/setup_iptables.sh"
  config.vm.provision "file", source: "./antidos.service", destination: "/$HOME/antidos.service"  
  config.vm.provision "shell" do |s|
    s.path = "umbox_setup.sh"
  end

  # Copy and setup Alerter.
  config.vm.provision "file", source: "../alerter", destination: "$HOME/"
  config.vm.provision "shell" do |s|
    s.path = "../alerter/alerter_setup.sh"
    s.args = ["/home/" + VM_USER + "/alerter"]
  end

end
