# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Box / OS
VAGRANT_BOX = 'generic/ubuntu1604'

VM_NAME = 'umbox-sniffer'
VM_USER = 'umbox'

PROGRAM_FOLDER = '/alerter'

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  # Vagrant box from Hashicorp
  config.vm.box = VAGRANT_BOX
  config.vm.hostname = VM_NAME

  # DHCP — comment this out if planning on using NAT instead
  config.vm.network "private_network", type: "dhcp"

  # Copy program and alerter.
  config.vm.provision "file", source: "../credential-sniffer", destination: "$HOME/credential-sniffer"
  config.vm.provision "file", source: "../alerter", destination: "$HOME/" + PROGRAM_FOLDER

  # Setup DNS resolution. This is needed to avoid issues with proxies when resolving names.
  config.vm.provision "shell", inline: <<-SHELL
    echo "nameserver 192.168.121.1" > /etc/resolv.conf
  SHELL

  # Setup dependencies and services.
  config.vm.provision "shell", path: "umbox_setup.sh"

end