# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Box / OS
VAGRANT_BOX = 'kalki/umbox-baseline'
VM_NAME = 'umbox-sniffer'

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  # Vagrant box from Hashicorp
  config.vm.box = VAGRANT_BOX
  config.vm.hostname = VM_NAME

  # Use libvirt's default DHCP private network.
  config.vm.network "private_network", type: "dhcp"

  # Copy program and alerter.
  config.vm.provision "file", source: "../credential-sniffer", destination: "$HOME/"
  config.vm.provision "file", source: "config_alerter.json", destination: "$HOME/alerter/config.json"

  # Setup dependencies and services.
  config.vm.provision "shell", path: "umbox_setup.sh"

end