# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Sets current start folder, and loads parent Vagrantfile
UMBOX_FOLDER = File.dirname(__FILE__)
VM_NAME = File.basename(UMBOX_FOLDER)
load File.expand_path(UMBOX_FOLDER + '/../../common/alerter_vm_base/Vagrantfile', __FILE__)

# All Vagrant configuration is done below.
Vagrant.configure(2) do |config|
  # Copy all files to the VM, and set up depdencies and service.
  config.vm.provision "file", source: UMBOX_FOLDER + "/setup_iptables.sh", destination: "$HOME/antidos/setup_iptables.sh"
  config.vm.provision "file", source: UMBOX_FOLDER + "/antidos.service", destination: "$HOME/antidos/antidos.service"
  config.vm.provision "shell" do |s|
    s.path = UMBOX_FOLDER + "/umbox_setup.sh"
  end

end