# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Box / OS
VAGRANT_BOX = 'generic/ubuntu1604'
VM_NAME = 'umbox-baseline'
VM_USER = 'vagrant'

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  # Vagrant box from Hashicorp
  config.vm.box = VAGRANT_BOX
  config.vm.hostname = VM_NAME

  # Use libvirt's default DHCP private network.
  config.vm.network "private_network", type: "dhcp"

  # Setup DNS resolution. This is needed to avoid issues with proxies when resolving names.
  # This IP is the gateway/DNS of the default libvirt network we are using.
  config.vm.provision "shell", inline: <<-SHELL
    echo "nameserver 192.168.121.1" > /etc/resolv.conf
  SHELL

  # NOTE: this is only needed if behind a proxy.
  config.vm.provision "shell", path: "proxy_setup.sh"

  # Setup general umbox things.
  config.vm.provision "shell", path: "umbox_setup.sh"

  # Copy alerter and setup Alerter.
  config.vm.provision "file", source: "../alerter", destination: "$HOME/"
  config.vm.provision "shell" do |s|
    s.path = "../alerter/alerter_setup.sh"
    s.args = ["/home/" + VM_USER + "/alerter"]
  end

end