# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# MODIFY THIS: Change this name to be better suited for the umbox.
VM_NAME = 'umbox-sniffer'

# All Vagrant configuration is done below.
Vagrant.configure(2) do |config|

  # Copy a properly configured alerter config file for this software to the VM.
  config.vm.provision "file", source: "../sniffer/config_alerter.json", destination: "$HOME/alerter/config.json"

  # Setup dependencies and services.
  config.vm.provision "shell", path: "../sniffer/umbox_setup.sh"

  # Copy all program files to the VM.
  config.vm.provision "file", source: "../../sniffer", destination: "$HOME/"
  config.vm.provision "file", source: "../sniffer/sniffer.service", destination: "$HOME/sniffer/sniffer.service"

  # Setup Sniffer deps.
  config.vm.provision "shell", path: "../sniffer/sniffer_setup.sh"

end

# Loads common_Vagrantfile
load File.expand_path('../../Vagrantfile.common', __FILE__)
