# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# MODIFY THIS: Change this name to be better suited for the umbox.
VM_NAME = 'umbox-sniffer'

UMBOX_FOLDER = File.basename(Dir.getwd)

# All Vagrant configuration is done below.
Vagrant.configure(2) do |config|

  # Copy all program files to the VM.
  config.vm.provision "file", source: "../../sniffer" + UMBOX_FOLDER, destination: "$HOME/"

end

# Loads common_Vagrantfile
load File.expand_path('../../Vagrantfile.common', __FILE__)
