# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Loads common_Vagrantfile
load File.expand_path('../../common/Vagrantfile', __FILE__)

# All Vagrant configuration is done below.
Vagrant.configure(2) do |config|

  # Copy a properly configured alerter config file for this software to the VM, and restart alerter.
  config.vm.provision "file", source: "../sniffer_base/config_alerter.json", destination: "$HOME/alerter/config.json"
  config.vm.provision "shell", inline: "systemctl restart alerter"

  # Copy all sniffer files to the VM, and set up depdencies and service.
  config.vm.provision "file", source: "../../sniffer", destination: "$HOME/"
  config.vm.provision "file", source: "../sniffer_base/sniffer.service", destination: "$HOME/sniffer/sniffer.service"
  config.vm.provision "shell" do |s|
    s.path = "../sniffer_base/sniffer_setup.sh"
    s.args = ["/home/" + VM_USER + "/sniffer"]
  end


end

