# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Sets current start folder, and loads parent Vagrantfile
UMBOX_FOLDER = File.dirname(__FILE__)
load File.expand_path(UMBOX_FOLDER + '/../snort_base/Vagrantfile', __FILE__)

$script = <<-SCRIPT
sudo cp snort/snort.conf /etc/snort/snort.conf
sudo cp snort/local.rules /etc/snort/rules/local.rules
sudo systemctl restart snort
SCRIPT

# All Vagrant configuration is done below.
Vagrant.configure(2) do |config|
  # Copy all files to the VM, and set up dependencies and service.
  config.vm.provision "file", source: UMBOX_FOLDER + "/snort.conf", destination: "$HOME/snort/snort.conf"
  config.vm.provision "file", source: UMBOX_FOLDER + "/local.rules", destination: "$HOME/snort/local.rules"
  config.vm.provision "shell", inline: $script

  # Copy a properly configured alerter config file for this software to the VM, and restart alerter.
  config.vm.provision "file", source: UMBOX_FOLDER + "/config_alerter.json", destination: "$HOME/alerter/config.json"
  config.vm.provision "shell", inline: "systemctl restart alerter"
end
